name=PicoSyslog
version=1.1.0
author=Michał Leśniewski
maintainer=Michał Leśniewski <mlesniew@gmail.com>
sentence=Lightweight syslog client for ESP8266 and ESP32
paragraph=Easy-to-use Arduino syslog client library with a Serial-compatible API that forwards logs to both Serial and a UDP syslog server.
category=Communication
url=https://github.com/mlesniew/PicoSyslog
architectures=esp8266,esp32
includes=PicoSyslog.h
